"""Modify Car Table

Revision ID: 4f7e0d8a6226
Revises: ff1ed8606c83
Create Date: 2023-10-24 15:13:13.609443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7e0d8a6226'
down_revision: Union[str, None] = 'ff1ed8606c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # Add 'Petrol' to the enum column using a raw SQL statement
    connection = op.get_bind()
    connection.execute("ALTER TABLE car MODIFY COLUMN fuelType ENUM('Gasoline', 'Diesel', 'Electric', 'Hybrid', 'Petrol')")





def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
