"""Remove fuelType column

Revision ID: fe3a4e16fcb5
Revises: 4f7e0d8a6226
Create Date: 2023-10-24 15:28:18.961777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe3a4e16fcb5'
down_revision: Union[str, None] = '4f7e0d8a6226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_column('car', 'fuelType') 


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
