"""create_car_table

Revision ID: ff1ed8606c83
Revises: 
Create Date: 2023-10-24 14:59:01.440391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1ed8606c83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'car',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('manufacturer', sa.String(50), nullable=True),
        sa.Column('modelName', sa.String(50), nullable=True),
        sa.Column('cc', sa.Integer(), nullable=True),
        sa.Column('onRoadPrice', sa.Integer(), nullable=True),
        sa.Column('seatingCapacity', sa.Integer(), nullable=True),
        sa.Column('gearBox', sa.Integer(), nullable=True),
        sa.Column('fuelType', sa.Enum('Gasoline', 'Diesel','petrol', name='fuel_types' ), nullable=True),
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
